# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-09 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafanadb',
            name='db_name',
            field=models.CharField(default='telegraf', max_length=100),
        ),
    ]
